sudo: required

language: bash

language: bash
before_script:
- sudo add-apt-repository -y ppa:pgavin/ghdl
- sudo apt-get -qq update
- sudo apt-get install -y ghdl
- sudo apt-get install -y python python-pip

script:
- cd TP3
- python run.py
